# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  common = <<-SHELL
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sed -ie '0,/#PermitRootLogin prohibit-password/s/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
  sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd    
  sudo systemctl restart sshd
  SHELL

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.box_url = "ubuntu/focal64"
    jenkins.vm.network :private_network, ip: "192.168.10.2"
    jenkins.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "jenkins"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
    jenkins.vm.provision :shell, :inline => common
    jenkins.vm.provision "shell", path: "install_jenkins.sh"
  end
  config.vm.define "srvdev" do |srvdev|
    srvdev.vm.box = "ubuntu/focal64"
    srvdev.vm.hostname = "srvdev"
    srvdev.vm.box_url = "ubuntu/focal64"
    srvdev.vm.network :private_network, ip: "192.168.10.3"
    srvdev.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "srvdev"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    srvdev.vm.provision :shell, :inline => common
  end
  config.vm.define "srvstage" do |srvstage|
    srvstage.vm.box = "ubuntu/focal64"
    srvstage.vm.hostname = "srvstage"
    srvstage.vm.box_url = "ubuntu/focal64"
    srvstage.vm.network :private_network, ip: "192.168.10.7"
    srvstage.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "srvstage"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    srvstage.vm.provision :shell, :inline => common
  end
  config.vm.define "srvprod" do |srvprod|
    srvprod.vm.box = "ubuntu/focal64"
    srvprod.vm.hostname = "srvprod"
    srvprod.vm.box_url = "ubuntu/focal64"
    srvprod.vm.network :private_network, ip: "192.168.10.4"
    srvprod.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "srvprod"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    srvprod.vm.provision :shell, :inline => common
  end
  config.vm.define "srvbdd" do |srvbdd|
    srvbdd.vm.box = "ubuntu/focal64"
    srvbdd.vm.hostname = "srvbdd"
    srvbdd.vm.box_url = "ubuntu/focal64"
    srvbdd.vm.network :private_network, ip: "192.168.10.6"
    srvbdd.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "srvbdd"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    srvbdd.vm.provision :shell, :inline => common
    srvbdd.vm.provision "shell", path: "install_srvbdd.sh"
  end
  config.vm.define "registry" do |registry|
    registry.vm.box = "ubuntu/focal64"
    registry.vm.hostname = "registry"
    registry.vm.box_url = "ubuntu/focal64"
    registry.vm.network :private_network, ip: "192.168.10.5"
    registry.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "registry"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    registry.vm.provision :shell, :inline => common
    registry.vm.provision "shell", path: "install_registry.sh"
  end
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "ubuntu/focal64"
    gitlab.vm.hostname = "gitlab"
    gitlab.vm.box_url = "ubuntu/focal64"
    gitlab.vm.network :private_network, ip: "192.168.10.10"
    gitlab.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "gitlab"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
    gitlab.vm.provision :shell, :inline => common
    gitlab.vm.provision "shell", path: "install_gitlab.sh"
  end
end