service_install_run_data_source_connection: "jdbc:mysql://192.168.10.6:3306/{{env}}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false  "
service_install_run_data_source_connection_user: "vagrant"
service_install_run_data_source_connection_password: "vagrant"